@baseUrl=http://localhost:5000/prefisso

GET {{baseUrl}}?name=pinco&age=30&ciao

###
GET {{baseUrl}}/users/10

###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Pinco",
    "age": 30
}

###
PUT {{baseUrl}}/users/15
Content-Type: application/json

{
    "name": "Pinco",
    "age": 25
}

###
DELETE {{baseUrl}}/users/10